defaults:
  outdir: "/gdrive/MyDrive/sd_anims_new"
  width: 512
  height: 512
  sampler_n: ""
models:
  path: "/gdrive/MyDrive/models"
  fallback_path: "/content/models"
  sd: "sd-v1-4.ckpt"
  GFPGAN: ""
  ESRGAN2x: ""
  ESRGAN4x: ""
configs:
  sd: "/content/stable-diffusion-gradio-anim-opt/configs/stable-diffusion/v1-inference.yaml"
